# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(644, 489)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tabWidget_main = QtWidgets.QTabWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.tabWidget_main.sizePolicy().hasHeightForWidth())
        self.tabWidget_main.setSizePolicy(sizePolicy)
        self.tabWidget_main.setMinimumSize(QtCore.QSize(0, 200))
        self.tabWidget_main.setObjectName("tabWidget_main")
        self.verticalLayout_2.addWidget(self.tabWidget_main)
        self.groupBox_main = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_main.sizePolicy().hasHeightForWidth())
        self.groupBox_main.setSizePolicy(sizePolicy)
        self.groupBox_main.setObjectName("groupBox_main")
        self.verticalLayout_2.addWidget(self.groupBox_main)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout_2.addLayout(self.gridLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 644, 26))
        self.menubar.setObjectName("menubar")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuSettings = QtWidgets.QMenu(self.menubar)
        self.menuSettings.setObjectName("menuSettings")
        self.menulanguage = QtWidgets.QMenu(self.menuSettings)
        self.menulanguage.setObjectName("menulanguage")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionFFB_Wheel_TMC_wizard = QtWidgets.QAction(MainWindow)
        self.actionFFB_Wheel_TMC_wizard.setObjectName("actionFFB_Wheel_TMC_wizard")
        self.actionDFU_Uploader = QtWidgets.QAction(MainWindow)
        self.actionDFU_Uploader.setObjectName("actionDFU_Uploader")
        self.actionSave_chip_config = QtWidgets.QAction(MainWindow)
        self.actionSave_chip_config.setEnabled(False)
        self.actionSave_chip_config.setObjectName("actionSave_chip_config")
        self.actionRestore_chip_config = QtWidgets.QAction(MainWindow)
        self.actionRestore_chip_config.setEnabled(False)
        self.actionRestore_chip_config.setObjectName("actionRestore_chip_config")
        self.actionErrors = QtWidgets.QAction(MainWindow)
        self.actionErrors.setObjectName("actionErrors")
        self.actionTranslateToZHCN = QtWidgets.QAction(MainWindow)
        self.actionTranslateToZHCN.setObjectName("actionTranslateToZHCN")
        self.actionEnglish = QtWidgets.QAction(MainWindow)
        self.actionEnglish.setObjectName("actionEnglish")
        self.menuHelp.addAction(self.actionErrors)
        self.menuHelp.addAction(self.actionAbout)
        self.menulanguage.addAction(self.actionTranslateToZHCN)
        self.menulanguage.addAction(self.actionEnglish)
        self.menuSettings.addAction(self.actionDFU_Uploader)
        self.menuSettings.addAction(self.actionSave_chip_config)
        self.menuSettings.addAction(self.actionRestore_chip_config)
        self.menuSettings.addAction(self.menulanguage.menuAction())
        self.menubar.addAction(self.menuSettings.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget_main.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox_main.setTitle(_translate("MainWindow", "System"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.menuSettings.setTitle(_translate("MainWindow", "Extras"))
        self.menulanguage.setTitle(_translate("MainWindow", "Select Language"))
        self.actionAbout.setText(_translate("MainWindow", "About"))
        self.actionFFB_Wheel_TMC_wizard.setText(_translate("MainWindow", "FFB Wheel TMC"))
        self.actionDFU_Uploader.setText(_translate("MainWindow", "DFU Uploader"))
        self.actionSave_chip_config.setText(_translate("MainWindow", "Save chip config"))
        self.actionRestore_chip_config.setText(_translate("MainWindow", "Load chip config"))
        self.actionErrors.setText(_translate("MainWindow", "Errors"))
        self.actionTranslateToZHCN.setText(_translate("MainWindow", "简体中文(Chinese)"))
        self.actionEnglish.setText(_translate("MainWindow", "English"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
